version: "3"

services:

  frontend_service:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - "8501:8501"

  backend_service:
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - "8000:8000"